version: 0.0.{build}
configuration: Release

before_build:
- cmd: nuget restore .\source\Pk.Spatial.sln

build:
  verbosity: normal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure:2UvNfuCS0FwWR4gtOjeVihCCir28bHEcr2kQlD7hpYXI0WFPCDjuXA3tCieyEwdm
  
test_script:
  - ps: .\tests\run_tests.bat

after_test:
    - cmd: .\libraries\NuGet\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:".\libraries\NuGet\xunit.runner.console.2.1.0\tools\xunit.console.x86.exe" -targetargs:"/noshadow .\tests\Pk.Spatial.Tests\bin\Release\Pk.Spatial.Tests.dll" -output:coverage.xml
    - cmd: .\libraries\NuGet\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  