version: 0.0.{build}
configuration: Release

before_build:
- cmd: nuget restore .\Pk.Spatial.sln

build:
  project: Pk.Spatial.sln
  verbosity: normal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: 2UvNfuCS0FwWR4gtOjeVihCCir28bHEcr2kQlD7hpYXI0WFPCDjuXA3tCieyEwdm
test_script:
  - ps: .\tests\run_tests.bat

after_test:
    - cmd: .\libraries\Nuget\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:".\libraries\Nuget\xunit.runner.console.2.1.0\tools\xunit.console.x86.exe" -targetargs:".\tests\Pk.Spatial.Tests\bin\Release\Pk.Spatial.Tests.dll" -output:coverage.xml
    - cmd: .\libraries\Nuget\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
